### ISSUE TITLE
Feature: Bash autocompletion

### ISSUE THREAD

**Issue by vdun** [BlackArch/sploitctl#5]

**Comment by noptrix** [comment]
ok. will be added

**Comment by PedroSFreitas** [comment]
I'll be working on that during this weekend.

**Comment by PedroSFreitas** [comment]
@vdun is this enough for completion? 
![image](https://user-images.githubusercontent.com/12863160/29237493-b070b760-7ef5-11e7-8347-f57b6907c33a.png)

note: I just ran three times the same thing...

**Comment by noptrix** [comment]
neat @PedroSFreitas
