### ISSUE TITLE
undefined symbol: git_worktree_prune_init_options

### ISSUE THREAD

**Issue by 65535a** [BlackArch/sploitctl#9]
I'm running Manjaro with Black Arch repositories. Sploitctl installs nicely with pacman but while running I get this:

>Error while loading dependencies: /usr/lib/python3.8/site-packages/_pygit2.cpython-38-x86_64-linux-gnu.so: undefined symbol: git_worktree_prune_init_options

Pygit2 is installed. Same thing once cloned from the git repo.

**Comment by aancw** [comment]
I think it's because of pygit2. Can you try to uninstall or upgrade pygit2?

**Comment by 65535a** [comment]
Ok, it was that easy. Solved, thank you so much!
